[pmbootstrap]
version = 3
work = /home/runner/.local/var/pmbootstrap
device = samsung-smt500
ui = phosh
hostname = slim-os
jobs = 4
build_default_device_arch = True
is_default_channel = True

# SSH-Key Konfiguration
ssh_keys = false
ssh_key_glob = ~/.ssh/postmarketos-dev.pub
