[pmbootstrap]
version = 3
work = /home/runner/.local/var/pmbootstrap
aports = /home/runner/.local/var/pmbootstrap/cache_git/pmaports
device = samsung-smt500
user = user
ui = phosh
hostname = slim-os
channel = edge
jobs = 4
build_default_device_arch = True
is_default_channel = True
timezone = UTC

# SSH-Key Konfiguration
ssh_keys = false
ssh_key_glob = ~/.ssh/postmarketos-dev.pub

[providers]

[mirrors]
